version: '3.1'
services:
#  wordpress:
#    image: wordpress
#    restart: always
#    ports:
#      - 8080:80
#    environment:
#      WORDPRESS_DB_HOST: db
#      WORDPRESS_DB_USER: plugindb
#      WORDPRESS_DB_PASSWORD: plugindb
#      WORDPRESS_DB_NAME: plugindb
#    volumes:
#      - wordpress:/var/www/html
#      - ./ca-etransaction:/var/www/html/wp-content/plugins/ca-etransaction
#    depends_on:
#      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: plugindb
      MYSQL_USER: plugindb
      MYSQL_PASSWORD: plugindb
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/etransaction/mysql
    ports:
    - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db

volumes:
  wordpress:
  db:

